### ISSUE TITLE
Админ

### ISSUE THREAD

**Issue by pavelzarubin** [Little-Pie/pie-server#1]
Добавь тестовую миграцию для админа, а то пока в курлы и в код не полезешь, непонятно как происходит авторизация.
Можешь в будущем добавить этап регистрации админа при первом запуске. Но это необязательно.

**Comment by pavelzarubin** [comment]
upd: Я нашел модуль Test. Ты можешь сделать запуск с заполнением и без заполнения базы

**Comment by Little-Pie** [comment]
У меня можно stack run писать с аргументом f, и тогда база заполнится

**Comment by Little-Pie** [comment]
В описании сервера я это указала

**Comment by pavelzarubin** [comment]
а тогда я не заметил
