### ISSUE TITLE
Не работает фильтр по названию

### ISSUE THREAD

**Issue by roman-bodavskiy** [Little-Pie/pie-server#18]
![Screenshot from 2022-12-12 20-25-47](https://user-images.githubusercontent.com/92144831/207117147-09b88b57-c146-4bb4-b177-59e946741c62.png)

**Comment by Little-Pie** [comment]
Хм, странно... Я сейчас пишу такой запрос, и мне выдает пустой список. Такой ответ как у тебя мне выдает по единственному фильтру author=Polina

**Comment by Little-Pie** [comment]
Может у тебя файл не сохранен был. У меня не получается найти, что тут не работает

**Comment by roman-bodavskiy** [comment]
Да, почему-то именно в sh файле не работает Ладно, на работоспособность сервера это не влияет
