### ISSUE TITLE
Pause

### ISSUE THREAD

**Issue by pavelzarubin** [Little-Pie/pie-server#6]
у меня в `bash`, `Pause`, не работает. Ты какой оболочкой пользуешься?

**Comment by Little-Pie** [comment]
У меня виндовс, и я curl в cmd делала, а по требованиям в ревью переделала на sh. Но, видимо, Pause туда не подходит. Как переделать?

**Comment by pavelzarubin** [comment]
а ну можешь его убрать, можешь оставить, он просто не работает, запросы проходят

**Comment by pavelzarubin** [comment]
я на Windows использовал cygwin, для sh-скриптов

**Comment by roman-bodavskiy** [comment]
у меня тоже не работает Pause
А еще сервер не выдает ошибку при неверном роуте, например http://localhost:4000/createCategory1

**Comment by roman-bodavskiy** [comment]
У меня тоже этот Pause не работает. Можешь убрать, пожалуйста?
